### ISSUE TITLE
Error in `domain` usage

### ISSUE THREAD

**Issue by lesion** [remotestorage/armadietto#1]
https://github.com/remotestorage/armadietto/blob/ea4d8edfe1b85ecf29e7c35585d23949cddb0ced/lib/armadietto.js#L58

➜ bin git:(master) ✗  ./server.js -c example.conf
[INFO] Starting remoteStorage: http://0.0.0.0:8000
/data/dev/rs/armadietto/lib/armadietto.js:58
      .add(res)
      ^

TypeError: Cannot read property 'add' of undefined
    at Server.handler (/data/dev/rs/armadietto/lib/armadietto.js:58:7)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)

**Comment by lesion** [comment]
fixed with 43bafa0b97a79ba48acd67361fa5a53c216f04d3
